
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const PRODUCT_ERROR = "PRODUCT_ERROR"
export const DELETE_PRODUCT = "DELETE_PRODUCT"